### ISSUE TITLE
Handling of brackets within where clause

### ISSUE THREAD

**Issue by quinlanmorake** [proullon/ramsql#27]
Currently, where clauses that have open / closing curly braces in them are not supported. 

If one modifies TestSelectStar to parser_test.go

func TestSelectStar(t *testing.T) {
	query := `SELECT * FROM account WHERE (email = 'foo@bar.com')`
	parse(query, 1, t)
}

one gets 

parser_test.go:232: Cannot parse tokens from 'SELECT * FROM account WHERE (email = 'foo@bar.com')': Syntax error near where ( email

**Comment by sneko** [comment]
Hi @quinlanmorake ,

Why did you close this? You found a solution?

**Comment by quinlanmorake** [comment]
Hi @sneko, 

This was a while back :D I believe I found documentation that said this was not going to be supported, I didn't have time to put together a proposed fix; so I just use a docker container and made my unit tests integration tests. 

Cia0

**Comment by sneko** [comment]
@quinlanmorake yeah I was about to switch over containers each time I have I/O on a third-party tool. Because that's too complex to find emulation for each tool (loosing time by the way, whereas and they will never match the original version)

Any tip from your experience? Was thinking to go with https://github.com/testcontainers/testcontainers-go since they have implementation for each language.

Thank you,
